apiVersion: v1
kind: Service
metadata:
  name: {{ include "cicd-demo.fullname" . | trunc 63 | trimSuffix "-" }}
  labels:
    app: cicd-demo
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
  - port: {{ default 80 .Values.service.port }}
    targetPort: {{ default 5000 .Values.service.targetPort }}
  selector:
    app: cicd-demo
